Merge sync node to develop, update monitors logic
skalenetwork/skale-admin pull request #1045
Opened 2024-02-07 19:30 UTC by dmytrotkk

2024-02-14 13:47 UTC, badrogger requested changes

2024-02-14 13:47 UTC, badrogger commented on core/schains/config/generator.py
> -        f'ecdsa keyname: {ecdsa_key_name}'
Suggest to remove keyname and add sync_node logging.

2024-02-14 13:47 UTC, badrogger commented on core/schains/config/node_info.py
> +        if self.archive is not None and self.sync_node:
Might be better to simply put true/false for archiveMode / syncFromCatchup.

2024-02-14 13:47 UTC, badrogger commented on core/schains/config/node_info.py
> +        logger.warning(f'Generating CurrentNodeInfo for {schain["name"]}, ecdsa_key_name is None')
It's not a warning if sync node=true, since it's expected. Also if for sync_node=false it's better to raise and exception.

2024-02-14 13:47 UTC, badrogger commented on core/schains/monitor/containers.py
> +    if SYNC_NODE:
I think this log line can be ommited.

2024-02-14 13:47 UTC, badrogger commented on core/schains/monitor/main.py
> +        logger.info('Sync node mode, running config checks')
Config check was executed before. It's better to remove the line

2024-02-14 13:47 UTC, badrogger commented on core/schains/monitor/skaled_monitor.py
> +            mon_type = ReloadGroupSkaledMonitor
What about ReloadIpSkaledMonitor?

2024-02-14 13:47 UTC, badrogger commented on tools/logger.py
> +    # for handler in logging.root.handlers[:]:
Better to remove

2024-02-14 13:47 UTC, badrogger commented on tools/configs/logs.py
> +SYNC_LOG_FORMAT = '[%(asctime)s %(levelname)s] - %(name)s:%(lineno)d - %(message)s'  # noqa
Suggest to use same log formant for regular and sync nodes.

2024-02-14 13:47 UTC, badrogger commented on tests/schains/cmd_test.py
> +    print(container_opts, 'IVD')
Please, remove

2024-02-14 13:47 UTC, badrogger commented on requirements.txt
> +urllib3<2
It's not necessary anymore.

2024-02-14 13:56 UTC, dmytrotkk commented on core/schains/config/generator.py
> -        f'ecdsa keyname: {ecdsa_key_name}'
addressed

2024-02-14 13:56 UTC, dmytrotkk commented on core/schains/config/node_info.py
> +        if self.archive is not None and self.sync_node:
addressed

2024-02-14 13:59 UTC, dmytrotkk commented on core/schains/config/node_info.py
> +        logger.warning(f'Generating CurrentNodeInfo for {schain["name"]}, ecdsa_key_name is None')
addressed

2024-02-14 19:37 UTC, dmytrotkk commented on core/schains/monitor/containers.py
> +    if SYNC_NODE:
fixed

2024-02-14 19:40 UTC, dmytrotkk commented on core/schains/monitor/main.py
> +        logger.info('Sync node mode, running config checks')
changed to `running config monitor`

2024-02-15 19:20 UTC, dmytrotkk commented on core/schains/monitor/skaled_monitor.py
> +            mon_type = ReloadGroupSkaledMonitor
added `ReloadIpSkaledMonitor` to sync node

2024-02-15 19:24 UTC, dmytrotkk commented on tools/logger.py
> +    # for handler in logging.root.handlers[:]:
removed

2024-02-15 19:25 UTC, dmytrotkk commented on tools/configs/logs.py
> +SYNC_LOG_FORMAT = '[%(asctime)s %(levelname)s] - %(name)s:%(lineno)d - %(message)s'  # noqa
changed to `ADMIN_LOG_FORMAT`

2024-02-15 19:26 UTC, dmytrotkk commented on tests/schains/cmd_test.py
> +    print(container_opts, 'IVD')
removed

2024-02-15 19:26 UTC, dmytrotkk commented on requirements.txt
> +urllib3<2
removed

2024-03-06 15:25 UTC, merged