Fix stuck monitor recovery. Avoid DB related deadlocks.
skalenetwork/skale-admin pull request #1098
Opened 2024-08-08 10:47 UTC by badrogger

**Changes:**
1. Added stuck recovery mechanism for config/skaled schains pipelines. 
2. Switch to writing alive timestamp to a file instead of the db. 
3. Remove locks from db read/write operations. 

**Performance:**
1. No additional major computation or IO operations were introduced. 
 
**Tests: **
1. Added unit tests. 
4. Tested on the local network.

2024-10-14 16:03 UTC, DimaStebaev approved these changes, later dismissed

2024-10-14 16:03 UTC, DimaStebaev commented on core/schains/monitor/main.py
> +STUCK_TIMEOUT = 60 * 60 * 2
Better to specify time units in the name

2024-10-14 16:03 UTC, DimaStebaev commented on core/schains/monitor/main.py
> +    STUCK_TIMEOUT = 3600  # 1 hour
STUCK_TIMEOUT_SECONDS

2024-10-14 16:03 UTC, DimaStebaev commented on core/schains/monitor/tasks.py
> +SLEEP_INTERVAL = 10
SLEEP_INTERVAL_SECONDS?

2024-10-14 16:03 UTC, DimaStebaev commented on core/schains/process_manager_helper.py
> -#   -*- coding: utf-8 -*-
Remove the file?

2024-10-16 11:23 UTC, DmytroNazarenko approved these changes, later dismissed

2024-10-16 11:42 UTC, dmytrotkk requested changes

2024-10-16 11:42 UTC, dmytrotkk commented on core/schains/process.py
> +TIMEOUT_COEFFICIENT = 2.2
unused variable

2024-10-16 11:42 UTC, dmytrotkk commented on core/schains/process.py
> +class ProcessReport:
does it make sense to move all basic functions, like save, save_tmp, update, move, etc, to the parent class that will be used for all json config files on the node?

2024-10-17 09:43 UTC, badrogger commented on core/schains/process.py
> +TIMEOUT_COEFFICIENT = 2.2
addressed

2024-10-17 09:43 UTC, badrogger commented on core/schains/monitor/tasks.py
> +SLEEP_INTERVAL = 10
addresses

2024-10-17 09:43 UTC, badrogger commented on core/schains/monitor/main.py
> +    STUCK_TIMEOUT = 3600  # 1 hour
addressed

2024-10-17 09:43 UTC, badrogger commented on core/schains/monitor/main.py
> +STUCK_TIMEOUT = 60 * 60 * 2
addressed

2024-10-17 10:52 UTC, badrogger commented on core/schains/process.py
> +class ProcessReport:
Suggest to do it in the next release.

2024-10-17 11:10 UTC, merged