Handle schain storage allocation type
skalenetwork/skale-admin pull request #1101
Opened 2024-08-21 12:25 UTC by badrogger

**Changes**
- Handle new allocation type schain options field.

**Tests**
- Tested on local network
- Modified existing unit tests. Added new ones.

**Performance**
- No performance related changes were introduced.

2024-08-29 19:06 UTC, dmytrotkk requested changes

2024-08-29 19:06 UTC, dmytrotkk commented on core/schains/limits.py
> +    return schain['allocationType'].name.lower()
can we use AllocationType enum values instead of str here and in all other places?

2024-08-29 19:06 UTC, dmytrotkk commented on core/schains/config/schain_info.py
>      schain_type = get_schain_type(schain['partOfNode'])
I think it makes sense to switch to object return value in `skale.schains.get` instead of dict, this will simplify our codebase a bit

2024-08-29 19:06 UTC, dmytrotkk commented on tools/schain_allocation.py
> +#   -*- coding: utf-8 -*-
if this code is not used in any way in the main skale-admin codebase, let's move it `tests` or `scripts` folder

2024-09-10 15:58 UTC, dmytrotkk approved these changes, later dismissed

2024-09-10 15:58 UTC, dmytrotkk commented on .github/workflows/test.yml
> +          ls -altr ../.venv
why do we need pwd and ls?

2024-09-10 15:58 UTC, dmytrotkk commented on tests/schain_allocation.py
> +#   along with SKALE.py.  If not, see <https://www.gnu.org/licenses/>.
should we change it to `skale-admin`?

2024-09-10 15:58 UTC, dmytrotkk commented on tests/schains/config/static_params_test.py
> +TS_FOR_ALL_NAME = 'revertableFSPatchTimestamp'
mb `DEFAULT_TS_NAME` and `CHAIN_SPECIFIC_TS_NAME`?
or something like this

2024-09-10 15:59 UTC, badrogger commented on .github/workflows/test.yml
> +          ls -altr ../.venv
will address it in another pr

2024-09-10 15:59 UTC, badrogger commented on tests/schains/config/static_params_test.py
> +TS_FOR_ALL_NAME = 'revertableFSPatchTimestamp'
will address it in another pr

2024-09-10 16:00 UTC, badrogger commented on tests/schain_allocation.py
> +#   along with SKALE.py.  If not, see <https://www.gnu.org/licenses/>.
will address it in another pr

2024-09-11 09:43 UTC, DimaStebaev commented on .github/workflows/test.yml
> +          uv pip install -r requirements-dev.txt
I like using of this action.
https://github.com/getsentry/action-setup-venv
It setups venv and drastically speeds up the process.

2024-09-11 09:43 UTC, DimaStebaev commented on core/schains/config/node_info.py
> +    """Returns camel-case representation of the CurrentNodeInfo object"""
🤔

2024-09-11 09:43 UTC, DimaStebaev commented on core/schains/limits.py
> +def get_schain_limit(schain_type: SchainType, metric_type: MetricType) -> dict:
I think it's better to use neither `TypedDict` or data object here.

2024-09-13 15:08 UTC, DimaStebaev submitted a review, later dismissed

2024-09-16 17:08 UTC, badrogger commented on tests/schains/config/static_params_test.py
> +TS_FOR_ALL_NAME = 'revertableFSPatchTimestamp'
changed

2024-09-16 17:09 UTC, badrogger commented on .github/workflows/test.yml
> +          ls -altr ../.venv
changed

2024-09-17 19:03 UTC, dmytrotkk approved these changes

2024-09-18 13:50 UTC, DimaStebaev approved these changes

2024-09-18 15:49 UTC, DmytroNazarenko approved these changes
Looks good to me, but double check that options are set in correct way in skaled: 
https://github.com/skalenetwork/skale-admin/issues/1064#issuecomment-2358789156

2024-09-18 15:50 UTC, merged