Nftables
skalenetwork/skale-admin pull request #1136
Opened 2024-11-18 16:16 UTC by badrogger

2024-12-26 18:30 UTC, DmytroNazarenko approved these changes, later dismissed

2024-12-27 20:15 UTC, dmytrotkk requested changes

2024-12-27 20:15 UTC, dmytrotkk commented on core/schains/firewall/firewall_manager.py
> +        nc_controller.create_table()
let's rename

2024-12-27 20:15 UTC, dmytrotkk commented on core/schains/firewall/nftables.py
> +T = TypeVar('T')
looks like `T = TypeVar('T')` is unused

2024-12-27 20:15 UTC, dmytrotkk commented on core/schains/firewall/nftables.py
> +        rc, output, error = self.run_json_cmd(json_cmd)
output is unused, can be replaced with `_`

2024-12-27 20:15 UTC, dmytrotkk commented on core/schains/firewall/nftables.py
> +    @classmethod
does it make sense to group all class methods and move them to the beginning or the end of the class?

2024-12-31 14:24 UTC, dmytrotkk approved these changes

2024-12-31 15:53 UTC, DmytroNazarenko approved these changes

2024-12-31 16:25 UTC, merged