Enhancement/skale 3030 restructure schain config
skalenetwork/skale-admin pull request #249
Opened 2020-08-09 17:05 UTC by dmitry-tk

2020-08-15 06:46 UTC, badrogger requested changes

2020-08-15 06:46 UTC, badrogger commented on core/schains/config/node_info.py
> +    for (i, value) in enumerate(common_public_keys):
Redundant brackets

2020-08-15 06:46 UTC, badrogger commented on core/schains/config/helper.py
> +#   -*- coding: utf-8 -*-
core.schains.config package contains utils and helper. Looks like ambiguity.

2020-08-17 10:46 UTC, dmitry-tk commented on core/schains/config/helper.py
> +#   -*- coding: utf-8 -*-
@badrogger going to rename it to `config_builder`

2020-08-19 13:51 UTC, merged