Enhancement/skale 3063 exit after rotation
skalenetwork/skale-admin pull request #274
Opened 2020-08-26 09:31 UTC by DmytroNazarenko

* Add additional check for restarted node

2020-08-26 09:42 UTC, badrogger approved these changes, later dismissed
Great!

2020-08-26 13:12 UTC, dmitry-tk requested changes
replace `check_container_exit` function with 2 functions `is_exited_with_zero` and `is_exited`

2020-08-26 13:12 UTC, dmytrotkk commented on core/schains/config/helper.py
> +    config_filepath = get_schain_config_filepath(schain_name, inside_skaled=True)
rename to `in_schain_container`. `skaled` term is not used in the skale-node.

2020-08-27 13:54 UTC, dmitry-tk approved these changes

2020-08-27 13:54 UTC, merged