Bug/skale 3165 fix wait for function
skalenetwork/skale-admin pull request #282
Opened 2020-09-04 14:06 UTC by olehnikolaiev

low risk
get broadcast data from events if sgx crashes
fir `wait_for_fail` function

2020-09-14 16:38 UTC, DmytroNazarenko requested changes

2020-09-14 16:38 UTC, DmytroNazarenko commented on tools/bls/dkg_client.py
> +            if len(tx_res.receipt['logs']) != 5:
Better move 5 to constants

2020-09-14 17:33 UTC, dmitry-tk requested changes

2020-09-14 17:33 UTC, dmitry-tk commented on tools/bls/dkg_client.py
> +            if len(tx_res.receipt['logs']) != 5:
agree

2020-09-14 17:33 UTC, dmitry-tk commented on tools/bls/dkg_client.py
>          self.incoming_secret_key_contribution[from_node] = broadcasted_data[1][
looks like this calculation is identical to the line 212/213 and looks pretty complicated.
mb it makes sense to move them to the separate function?

2020-09-14 18:06 UTC, olehnikolaiev commented on tools/bls/dkg_client.py
>          self.incoming_secret_key_contribution[from_node] = broadcasted_data[1][
fixed

2020-09-14 20:28 UTC, DmytroNazarenko approved these changes, later dismissed
Great!

2020-09-15 07:32 UTC, DmytroNazarenko approved these changes

2020-09-15 08:23 UTC, dmitry-tk approved these changes
great

2020-09-15 08:23 UTC, merged