Enhancement/skale 3272 repair mode
skalenetwork/skale-admin pull request #309
Opened 2020-10-01 08:26 UTC by badrogger

2020-10-05 10:37 UTC, dmitry-tk requested changes

2020-10-05 10:37 UTC, dmytrotkk commented on core/schains/cleaner.py
> +            logger.warning(f'Removing secret_key for rotation {i} failed',
why `logger.warning` and not `logger.exception`?

2020-10-05 11:27 UTC, badrogger commented on core/schains/cleaner.py
> +            logger.warning(f'Removing secret_key for rotation {i} failed',
adressed

2020-10-05 11:32 UTC, dmitry-tk approved these changes, later dismissed
Great!

2020-10-05 14:56 UTC, DmytroNazarenko requested changes

2020-10-05 14:56 UTC, DmytroNazarenko commented on core/schains/cleaner.py
> +def remove_schain_volume(schain_name, dutils=None):
Mb add type of params like in remove_schain_container

2020-10-05 14:56 UTC, DmytroNazarenko commented on core/schains/creator.py
> +        logger.info(f'Running monitor for sChain {name} in REGULAR mode')
Let's unify logger.info(f'Running monitor for sChain {name} in {mode} mode')

2020-10-05 14:56 UTC, DmytroNazarenko commented on core/schains/volume.py
> +    return {f'{name}': {'bind': mount_path, 'mode': 'Z'}}
'mode': 'Z' -> 'mode': mode

2020-10-05 14:56 UTC, DmytroNazarenko commented on scripts/run_tests.sh
> +# rm -r $SGX_CERTIFICATES_FOLDER
Uncomment or remove

2020-10-05 14:56 UTC, DmytroNazarenko commented on tests/conftest.py
> +    return 'schain_' + get_random_string()
schain_name should be without 'schain' prefix

2020-10-05 14:56 UTC, DmytroNazarenko commented on tests/firewall/run_test.py
> +# @pytest.mark.skip('Problems with github actions')
Mb remove?

2020-10-05 17:31 UTC, badrogger commented on tests/firewall/run_test.py
> +# @pytest.mark.skip('Problems with github actions')
addressed

2020-10-05 17:31 UTC, badrogger commented on tests/conftest.py
> +    return 'schain_' + get_random_string()
addressed

2020-10-05 17:31 UTC, badrogger commented on scripts/run_tests.sh
> +# rm -r $SGX_CERTIFICATES_FOLDER
addressed

2020-10-05 17:31 UTC, badrogger commented on core/schains/volume.py
> +    return {f'{name}': {'bind': mount_path, 'mode': 'Z'}}
addressed

2020-10-05 17:31 UTC, badrogger commented on core/schains/creator.py
> +        logger.info(f'Running monitor for sChain {name} in REGULAR mode')
addressed

2020-10-05 17:31 UTC, badrogger commented on core/schains/cleaner.py
> +def remove_schain_volume(schain_name, dutils=None):
addressed

2020-10-05 20:17 UTC, DmytroNazarenko requested changes

2020-10-05 20:17 UTC, DmytroNazarenko commented on core/schains/creator.py
> +                f'Finish time: {finish_time}')
Finish time log doesn't  need for REGULAR MonitorNode

2020-10-06 05:29 UTC, badrogger commented on core/schains/creator.py
> +                f'Finish time: {finish_time}')
addressed

2020-10-06 05:31 UTC, DmytroNazarenko approved these changes

2020-10-06 11:00 UTC, dmitry-tk approved these changes

2020-10-06 11:08 UTC, merged