SKALE-3580 API changes WIP
skalenetwork/skale-admin pull request #351
Opened 2020-11-27 10:44 UTC by dmitry-tk

2020-12-04 10:54 UTC, badrogger requested changes

2020-12-04 10:54 UTC, badrogger commented on scripts/install_python_dependencies.sh
> +#!/usr/bin/env bash
Bad naming for file that spins up sgx and redis containers.

2020-12-04 10:54 UTC, badrogger commented on tests/docker_utils_test.py
> +        _all=True
_var syntax is for private variables. To fix linter better to use all_.

2020-12-04 10:54 UTC, badrogger commented on web/routes/node_exit.py
>  def construct_node_exit_bp(node):
let's consider to merge it with node blueprint. I think skale exit is confusing.

2020-12-04 10:54 UTC, badrogger commented on web/routes/health.py
> +    @health_bp.route(get_api_url(BLUEPRINT_NAME, 'schains-checks'), methods=['GET'])
May be we can leave just /health/schains instead of schains-checks ?

2020-12-14 16:46 UTC, dmitry-tk commented on scripts/install_python_dependencies.sh
> +#!/usr/bin/env bash
addressed

2020-12-14 16:48 UTC, dmitry-tk commented on tests/docker_utils_test.py
> +        _all=True
but otherwise we're redefining built-in `all`

2020-12-14 17:39 UTC, dmitry-tk commented on web/routes/node_exit.py
>  def construct_node_exit_bp(node):
merged

2020-12-14 17:51 UTC, dmitry-tk commented on web/routes/health.py
> +    @health_bp.route(get_api_url(BLUEPRINT_NAME, 'schains-checks'), methods=['GET'])
renamed

2020-12-15 09:14 UTC, badrogger approved these changes

2020-12-15 10:58 UTC, merged