Enhancement/skale 3775 ima register
skalenetwork/skale-admin pull request #419
Opened 2021-01-22 16:14 UTC by DmytroNazarenko

2021-01-22 16:25 UTC, badrogger requested changes

2021-01-22 16:25 UTC, badrogger commented on core/schains/creator.py
> +def monitor_schain(skale, skale_ima, node_info, schain, ecdsa_sgx_key_name):
I think we need to spawn new instance of skale_ima here.

2021-01-24 15:13 UTC, badrogger approved these changes, later dismissed

2021-01-24 15:57 UTC, badrogger submitted a review, later dismissed

2021-04-16 15:53 UTC, badrogger approved these changes

2021-04-19 15:50 UTC, dmitry-tk approved these changes

2021-04-19 15:51 UTC, merged