Enhancement/skale 4212 filestorage https
skalenetwork/skale-admin pull request #568
Opened 2021-05-27 17:04 UTC by DmytroNazarenko

* Regenerate nginx config after ssl upload

2021-05-28 11:51 UTC, badrogger requested changes

2021-05-28 11:51 UTC, badrogger commented on core/schains/ssl.py
> +def check_ssl_certs():
`is_ssl_folder_empty` serves the same purpose

2021-05-28 11:51 UTC, badrogger commented on web/routes/ssl.py
> +        generate_nginx_config()
It's better to add error handling here. If nginx reloading failed we still can reload schains.

2021-05-28 11:51 UTC, badrogger commented on core/nginx.py
> +    nginx_container.restart()
I suggest to move restarting to separate function in order to test them separately.

2021-05-28 16:27 UTC, DmytroNazarenko commented on core/schains/ssl.py
> +def check_ssl_certs():
We need to check both key and cert

2021-05-31 17:09 UTC, badrogger approved these changes

2021-05-31 17:14 UTC, dmitry-tk approved these changes

2021-05-31 17:14 UTC, merged