SKALE-4829 Add predeployeds, restructure predeployed accounts
skalenetwork/skale-admin pull request #721
Opened 2021-12-22 18:07 UTC by dmitry-tk

2021-12-24 17:19 UTC, badrogger requested changes

2021-12-24 17:19 UTC, badrogger commented on core/schains/config/accounts.py
> +    assert isinstance(code, str) or code is None
Are assertions really needed here ?

2021-12-24 20:00 UTC, dmitry-tk commented on core/schains/config/accounts.py
> +    assert isinstance(code, str) or code is None
legacy code, I'll remove it

2021-12-28 16:23 UTC, badrogger approved these changes

2021-12-28 16:25 UTC, merged