Feature/skale 4698 Add interface between skaled and skale-admin
skalenetwork/skale-admin pull request #733
Opened 2022-01-10 15:31 UTC by dmitry-tk

2022-01-11 09:10 UTC, badrogger requested changes

2022-01-11 09:10 UTC, badrogger commented on core/schains/skaled_status.py
> +    def is_exit_time_reached(self):
Suggest to rename to exit_time_reached or make it a function.

2022-01-11 09:10 UTC, badrogger commented on tests/conftest.py
> +    }.copy()
Why do we need copy here ?

2022-01-11 16:54 UTC, dmitry-tk commented on tests/conftest.py
> +    }.copy()
removed

2022-01-11 16:54 UTC, dmitry-tk commented on core/schains/skaled_status.py
> +    def is_exit_time_reached(self):
renamed

2022-01-12 20:24 UTC, badrogger requested changes

2022-01-12 20:24 UTC, badrogger commented on core/schains/monitor/rpc.py
> +    if skaled_status.exit_time_reached:
I think It's better to reset rpc restart counter in both conditions

2022-01-12 20:24 UTC, badrogger commented on core/schains/monitor/rpc.py
> +    if skaled_status.downloading_snapshot:
Not sure if it's expected, but monitor_container from core.schains.runner still relies on container exit codes. Should it be changed?

2022-01-13 13:35 UTC, dmitry-tk commented on core/schains/monitor/rpc.py
> +    if skaled_status.exit_time_reached:
added

2022-01-13 13:38 UTC, dmitry-tk commented on core/schains/monitor/rpc.py
> +    if skaled_status.downloading_snapshot:
you mean `is_schain_container_failed(schain_name, dutils=dutils)` from `core.schains.monitor.containers`?

2022-01-13 14:49 UTC, dmitry-tk commented on core/schains/monitor/rpc.py
> +    if skaled_status.downloading_snapshot:
fixed

2022-01-14 13:58 UTC, badrogger approved these changes, later dismissed

2022-01-14 16:47 UTC, merged