SKALE-799 Sync node functionality
skalenetwork/skale-admin pull request #810
Opened 2022-05-12 18:58 UTC by dmitry-tk

2022-05-17 15:24 UTC, badrogger requested changes

2022-05-17 15:24 UTC, badrogger commented on tools/logger.py
> +    for handler in logging.root.handlers[:]:
What is the purpose of this change?

2022-05-17 15:24 UTC, badrogger commented on sync/main.py
> +    dutils = DockerUtils(volume_driver='local', host='unix:///var/run/docker.sock')  # TODO: TMP!
There is no such socket inside the container

2022-05-17 15:24 UTC, badrogger commented on sync_node.py
> +    logger.info('aaa!gdfxgdsfgsdf')
Should be removed

2022-05-17 15:24 UTC, badrogger commented on sync_node.py
> +    node_config.id = schain_nodes[0]
Is it safe? Does skaled require real node id ?

2022-05-17 15:24 UTC, badrogger commented on sync/main.py
> +    rc = get_default_rule_controller(
Why we cannot pass None here?

2022-05-19 19:10 UTC, dmitry-tk commented on tools/logger.py
> +    for handler in logging.root.handlers[:]:
logger doesn't work because some module tries to log before the logger is initialized.
https://stackoverflow.com/a/2588054

2022-05-19 19:10 UTC, dmitry-tk commented on sync/main.py
> +    dutils = DockerUtils(volume_driver='local', host='unix:///var/run/docker.sock')  # TODO: TMP!
debug line, removed

2022-05-19 19:11 UTC, dmitry-tk commented on sync_node.py
> +    logger.info('aaa!gdfxgdsfgsdf')
removed

2022-05-19 19:11 UTC, dmitry-tk commented on sync_node.py
> +    node_config.id = schain_nodes[0]
safe, node id should be provided cause it's required in config scheme, but not used in sync node

2022-05-19 19:12 UTC, dmitry-tk commented on sync/main.py
> +    rc = get_default_rule_controller(
you're right, removed

2022-05-20 12:10 UTC, badrogger approved these changes

2022-05-20 12:13 UTC, merged