Add abi check for watchdog
skalenetwork/skale-admin pull request #813
Opened 2022-05-16 15:46 UTC by alexgex

2022-05-17 11:46 UTC, badrogger requested changes

2022-05-17 11:46 UTC, badrogger commented on core/node.py
> +    return hashlib.sha256(open(file_path, 'rb').read()).hexdigest()
it's better to use context manager

2022-05-17 12:54 UTC, alexgex commented on core/node.py
> +    return hashlib.sha256(open(file_path, 'rb').read()).hexdigest()
oh, thanks, was in a hurry

2022-05-19 12:15 UTC, badrogger approved these changes

2022-05-19 17:57 UTC, dmitry-tk approved these changes

2022-05-20 08:56 UTC, merged