Enhancement/move schain static params to env
skalenetwork/skale-admin pull request #898
Opened 2022-12-12 21:48 UTC by dmytrotkk

2022-12-13 18:27 UTC, badrogger requested changes

2022-12-13 18:27 UTC, badrogger commented on tools/docker_utils.py
> +        if to_loggger:
Suggest to remove

2022-12-13 18:27 UTC, badrogger commented on core/schains/config/env_params.py
> +#   -*- coding: utf-8 -*-
suggest to rename to static_params.py

2022-12-14 13:29 UTC, dmytrotkk commented on tools/docker_utils.py
> +        if to_loggger:
addressed

2022-12-14 13:29 UTC, dmytrotkk commented on core/schains/config/env_params.py
> +#   -*- coding: utf-8 -*-
addressed

2022-12-14 15:48 UTC, badrogger approved these changes

2022-12-14 15:52 UTC, merged