Split monitor process for config and skaled
skalenetwork/skale-admin pull request #945
Opened 2023-06-16 14:50 UTC by badrogger

2023-06-19 18:19 UTC, dmytrotkk commented
Need to change the way skaled's are started after update

2023-06-20 17:05 UTC, dmytrotkk requested changes

2023-06-20 17:05 UTC, dmytrotkk commented on core/schains/checks.py
> +    def new_schain(self) -> CheckRes:
missing `@property` decorator for this check

2023-06-20 17:05 UTC, dmytrotkk commented on core/schains/checks.py
>      def is_healthy(self):
`is_healthy` is the same for both child classes, also this implementation misses returning type def

2023-06-20 17:05 UTC, dmytrotkk commented on core/schains/checks.py
> +class SChainChecks(IChecks):
do we need SChainChecks class in the new version?

it's used only twice in the project, in the cleaner module and in routes, and may be replaced with config checks + skaled checks objects 

also, the structure of SChainChecks makes it impossible to jump to the definition

just a suggestion, not critical

2023-06-20 18:19 UTC, badrogger commented on core/schains/checks.py
>      def is_healthy(self):
addressed

2023-06-20 18:19 UTC, badrogger commented on core/schains/checks.py
> +    def new_schain(self) -> CheckRes:
addressed

2023-06-20 18:21 UTC, badrogger commented on core/schains/checks.py
> +class SChainChecks(IChecks):
Cleaner is critical thing that can be untouched here. And API is not so critical thing that can work with such workaround for a while. 
Therefore suggest to change it only in case critical bugs are be found.

2023-06-20 19:13 UTC, DmytroNazarenko approved these changes

2023-06-20 20:12 UTC, merged